"""add admins and print options

Revision ID: 281a9098cb38
Revises: b76e4266cb5b
Create Date: 2026-08-30 02:35:27.943535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281a9098cb38'
down_revision: Union[str, Sequence[str], None] = 'b76e4266cb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('print_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('color_mode', sa.String(length=30), nullable=False),
    sa.Column('paper_size', sa.String(length=20), nullable=False),
    sa.Column('paper_type', sa.String(length=30), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('scaling', sa.String(length=30), nullable=False),
    sa.Column('collation_enabled', sa.Boolean(), nullable=False),
    sa.Column('photo_collage', sa.Boolean(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['print_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_options')
    op.drop_table('admins')
    # ### end Alembic commands ###
