"""add pricing rules

Revision ID: bec781e90613
Revises: 281a9098cb38
Create Date: 2026-09-24 23:57:00.250257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec781e90613'
down_revision: Union[str, Sequence[str], None] = '281a9098cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_mode', sa.String(length=30), nullable=False),
    sa.Column('paper_size', sa.String(length=20), nullable=False),
    sa.Column('paper_type', sa.String(length=30), nullable=False),
    sa.Column('duplex', sa.Boolean(), nullable=False),
    sa.Column('price_per_page', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
